ecom_project/ecom_app/urls.py
from django.urls import path
from . import views

app_name = 'ecom_app'

urlpatterns = [
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('update_item/', views.updateItem, name='update_item'),
    path('process_order/', views.processOrder, name='process_order'),
]

ecom_project/ecom_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecom_app.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom_project/ecom_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=True)
    transaction_id = models.CharField(max_length=200, null=True)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

    def __str__(self):
        return str(self.id)


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.address

ecom_project/ecom_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
import datetime
from .models import *

from . utils import cookieCart, cookieData, guestOrder

# Create your views here.


def store(request):
    data = cookieData(request)
    cartItems = data['cartItems']
    products = Product.objects.all()
    context = {'products': products, 'cartItems': cartItems}
    return render(request, 'ecom_app/store.html', context)


def cart(request):
    data = cookieData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'ecom_app/cart.html', context)


def checkout(request):
    data = cookieData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']
    context = {'items': items, 'order': order, 'cartItems': cartItems}
    return render(request, 'ecom_app/checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('productId:', productId)
    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
        customer=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(
        order=order, product=product)
    if action == 'add':
        orderItem.quantity = (orderItem.quantity+1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity-1)
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)


def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(
            customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
    order.save()
    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode'],
        )

    return JsonResponse('Payment completed', safe=False)

ecom_project/ecom_app/templates/ecom_app/cart.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'ecom_app:store' %}">Continue Shopping</a>
            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items : <strong>{{order.get_cart_items}}</strong></h5></th>
                    <th><h5>Total : <strong>₹{{order.get_cart_total|floatformat:2}}</strong></h5></th>
                    <th>
                        <a style="float: right;margin: 5px;" class="btn btn-success"  href="{% url 'ecom_app:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>
        </div>
        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>

            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2"><p>{{item.product.name}}</p></div>
                <div style="flex:1"><p>₹{{item.product.price|floatformat:2}}</p></div>
                <div style="flex:1"><p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/uparrow.png' %}">
                        <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/downarrow.png' %}">
                    </div>
                </div>
                <div style="flex:1"><p>₹{{item.get_total|floatformat:2}}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock content %}

ecom_project/ecom_app/templates/ecom_app/checkout.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                {% csrf_token %}
                <div id="user-info">
                    <p>User Information:</p>
                    <hr>
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>

        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
            <hr>
            <div id="paypal-button-container"></div>
            <button id="make-payment" class="btn btn-success btn-block">Make Payment</button>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'ecom_app:cart' %}">Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p>₹{{item.product.price|floatformat:2}}</p>
                </div>
                <div style="flex:1">
                    <p>x{{item.quantity}}</p>
                </div>
            </div>
            {% endfor %}
            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: ₹{{order.get_cart_total|floatformat:2}}</h5>
        </div>
    </div>
</div>
<!-- <script src="https://www.paypal.com/sdk/js?client-id=AQ8XM2Ht_2K4xGVHmYpLC23iCMScsLbu3kiY4ZDxA3JsoTPUKFNuSs0EB8PNln7VWVuEjnNUKL5NxeAC&currency=INR"></script>

<script>
    var total='{{order.get_cart_total}}'
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({
        style: {
            color: 'blue',
            shape: 'pill',

        },

        // Set up the transaction
        createOrder: function (data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function (data, actions) {
            return actions.order.capture().then(function (details) {
                submitFormData()
            });
        }

    }).render('#paypal-button-container');
</script> -->
<script type="text/javascript">
    var shipping = '{{order.shipping}}'
    var total = '{{order.get_cart_total|floatformat:2}}'
    if(shipping == 'False'){
        document.getElementById('shipping-info').innerHTML=''
        }
    if (user != 'AnonymousUser'){
        document.getElementById('user-info').innerHTML=''
    }
    if (shipping == 'False' && user != 'AnonymousUser'){
        document.getElementById('form-wrapper').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    }
    var form = document.getElementById('form')

//   csrftoken = form.getElementsByTagName("input")[0].value
//     console.log('Newtoken:', form.getElementsByTagName("input")[0].value)

    form.addEventListener('submit',function(e){  
        e.preventDefault()
        console.log('Form submitted...')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')
    })
    document.getElementById('make-payment').addEventListener('click',function(e){
        console.log('104')
        submitFormData()
    })
    function submitFormData(){
        var userFormData = {
            'name': null,
            'email': null,
            'total': total,
        }
        var shippingInfo ={
            'address':null,
            'city': null,
            'state': null,
            'zipcode': null,    
        }
        if(shipping != 'False'){
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }
        if(user == 'AnonymousUser'){
            userFormData.name = form.name.value
            userFormData.email = form.name.value
        }
        console.log('Payment button clicked')
    
        var url = '/process_order/'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body:JSON.stringify({ 'form': userFormData, 'shipping': shippingInfo })
        })
        .then((response) => response.json())
        .then((data) => {
            console.log('Success:',data);
            alert('Transaction completed');
            cart = {}
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
            window.location.href ="{% url 'ecom_app:store' %}"
        })
    }
</script>
{% endblock content %}

ecom_project/ecom_app/templates/ecom_app/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1">
    <title>Ecom Website</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">   
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="shortcut icon" href="#" />
    <script type="text/javascript">
    var user ="{{request.user}}"
    function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getToken('csrftoken');

    function getCookie(name){
        var cookieArr = document.cookie.split(";");
        for(var i=0;i<cookieArr.length;i++){
            var cookiePair = cookieArr[i].split("=");
            if(name == cookiePair[0].trim()){
                return decodeURIComponent(cookiePair[1]);
            }
        }
        return null;
    }
    var cart = JSON.parse(getCookie('cart'))
    if(cart == undefined){
        cart = {}
        document.cookie = 'cart='+JSON.stringify(cart) + ";domain=;path=/"
    }
    console.log("Cart:",cart)        
    </script>
</head>
<body >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'ecom_app:store' %}">Ecom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'ecom_app:store' %}">Store <span class="sr-only">(current)</span></a>
                </li>    
            </ul>
            <div class="form-inline my-2 my-lg-0">
                <a href="{% url 'ecom_app:cart' %}">
                    <img id="cart-icon" src="{% static 'images/cart.png' %}">
                </a>
                <p id="cart-total">{{cartItems}}</p>   
            </div>
        </div>
    </nav>
    <div class="container">
        <br>
        {% block content %}
    
    
        {% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

ecom_project/ecom_app/templates/ecom_app/store.html
{% extends 'ecom_app/main.html' %}
{% load static %}
{% block content %}
<div class="row">
    {% for product in products %}
    <div style="padding-bottom: 10px;" class="col-lg-3">
        <img class="thumbnail" src="{{product.imageURL}}" >
        <div class="box-element product">    
            <h6 ><strong>{{product.name}}</strong></h6>
            <h4 style="float:inline-end;font-size: 20px;"><strong>₹{{product.price|floatformat:2}}</strong></h4>
            <hr>
            <button style="width: 120px;" data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
            <a class="btn btn-outline-success" href="#">View</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}